# Generated by Django 2.2.5 on 2019-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.URLField(blank=True, null=True),
        ),
    ]
