# Generated by Django 2.2.5 on 2019-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0006_auto_20191018_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('listing_id', models.BigIntegerField()),
                ('guest_id', models.BigIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
            ],
        ),
    ]
